"""add jobs table

Revision ID: f8efb78c78df
Revises: e35e0a15f21e
Create Date: 2025-06-13 21:28:36.022757

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f8efb78c78df'
down_revision = 'e35e0a15f21e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
